/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HW;

import javax.swing.JOptionPane;

/**
 *
 * @author Josue Gavidia
 */
public class MAIN extends javax.swing.JFrame {

    /**
     * Creates new form MAIN
     */
    Transito transit;
    Multa temp;
    public MAIN() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        Crear.setVisible(false);
        Registro.setVisible(false);
        DatosSistema.setVisible(false);
        Pagar.setVisible(false);
        transit = new Transito();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        DatosSistema = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        printerTwo = new javax.swing.JTextArea();
        volver2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Registro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        printer = new javax.swing.JTextArea();
        volver1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Crear = new javax.swing.JPanel();
        code = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        type = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addMulta = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        Pagar = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        printerThree = new javax.swing.JTextArea();
        volver3 = new javax.swing.JButton();
        pay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        menu.setBackground(new java.awt.Color(51, 0, 0));
        menu.setPreferredSize(new java.awt.Dimension(564, 442));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Detalles del sistema");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        menu.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 160, 40));

        jButton5.setText("Agregar Multa");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        menu.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 120, 40));

        jButton6.setText("Registro Historico");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        menu.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 140, 40));

        jButton7.setText("Pagar Multa");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        menu.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 120, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TRANSITO");
        menu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        DatosSistema.setBackground(new java.awt.Color(51, 0, 0));
        DatosSistema.setPreferredSize(new java.awt.Dimension(564, 442));
        DatosSistema.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        printerTwo.setColumns(20);
        printerTwo.setRows(5);
        jScrollPane2.setViewportView(printerTwo);

        DatosSistema.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 340, 240));

        volver2.setText("Regresar");
        volver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver2ActionPerformed(evt);
            }
        });
        DatosSistema.add(volver2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ESTADISTICAS");
        DatosSistema.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        Registro.setBackground(new java.awt.Color(51, 0, 0));
        Registro.setPreferredSize(new java.awt.Dimension(564, 442));
        Registro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        printer.setColumns(20);
        printer.setRows(5);
        jScrollPane1.setViewportView(printer);

        Registro.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 380, 210));

        volver1.setText("Regresar");
        volver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver1ActionPerformed(evt);
            }
        });
        Registro.add(volver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MULTAS");
        Registro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        Crear.setBackground(new java.awt.Color(51, 0, 0));
        Crear.setPreferredSize(new java.awt.Dimension(564, 442));
        Crear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Crear.add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 230, 30));
        Crear.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 230, 30));

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LEVE", "MEDIO", "GRAVE" }));
        type.setSelectedItem("");
        Crear.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INFRACTOR");
        Crear.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CODIGO");
        Crear.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        addMulta.setText("Agregar");
        addMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMultaActionPerformed(evt);
            }
        });
        Crear.add(addMulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 160, 60));

        volver.setText("Regresar");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        Crear.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, -1, -1));

        Pagar.setBackground(new java.awt.Color(51, 0, 0));
        Pagar.setPreferredSize(new java.awt.Dimension(564, 442));
        Pagar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        Pagar.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 280, 40));

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Pagar.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 70, 40));

        printerThree.setColumns(20);
        printerThree.setRows(5);
        jScrollPane3.setViewportView(printerThree);

        Pagar.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 290, 100));

        volver3.setText("Regresar");
        volver3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver3ActionPerformed(evt);
            }
        });
        Pagar.add(volver3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, -1, -1));

        pay.setText("Pagar");
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });
        Pagar.add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 130, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Crear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 6, Short.MAX_VALUE)
                    .addComponent(Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DatosSistema, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Pagar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Crear, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Registro, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DatosSistema, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Pagar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMultaActionPerformed
        String tipo = type.getSelectedItem().toString();
        String codigo = code.getText();
        String nombre = name.getText();
        
        if (!tipo.equals(" ") && !code.getText().isBlank() && nombre != null) {
            
            transit.crearMulta(Integer.parseInt(codigo), nombre, tipo);
        } else {
            JOptionPane.showMessageDialog(null, "LLENE TODAS LAS CASILLAS");
        }

    }//GEN-LAST:event_addMultaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Crear.setVisible(true);
        menu.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        Crear.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_volverActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        menu.setVisible(false);
        Registro.setVisible(true);
        transit.imprimirMultas(printer);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void volver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver1ActionPerformed
        menu.setVisible(true);
        Registro.setVisible(false);
    }//GEN-LAST:event_volver1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DatosSistema.setVisible(true);
        menu.setVisible(false);
        transit.datosHistoricos(printerTwo);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void volver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver2ActionPerformed
        DatosSistema.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_volver2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    
        if (!search.getText().isBlank()) {
            temp=transit.buscarMulta(Integer.parseInt(search.getText()));
            
            if(temp!=null){
                  printerThree.setText(temp.print());
            }else{
                 JOptionPane.showMessageDialog(null, "NO EXISTE ESA MULTA");
            }
          
        } else {
            JOptionPane.showMessageDialog(null, "LLENE TODOS LOS CAMPOS");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       menu.setVisible(false);
       Pagar.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        
    }//GEN-LAST:event_searchActionPerformed

    private void volver3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver3ActionPerformed
        temp=null;
        menu.setVisible(true);
        Pagar.setVisible(false);
    }//GEN-LAST:event_volver3ActionPerformed

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        if(temp!=null){
            temp.pay();
        }else{
            JOptionPane.showMessageDialog(null, "BUSQUE UNA MULTA PARA PAGAR");
        }
    }//GEN-LAST:event_payActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Crear;
    private javax.swing.JPanel DatosSistema;
    private javax.swing.JPanel Pagar;
    private javax.swing.JPanel Registro;
    private javax.swing.JButton addMulta;
    private javax.swing.JTextField code;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel menu;
    private javax.swing.JTextField name;
    private javax.swing.JButton pay;
    private javax.swing.JTextArea printer;
    private javax.swing.JTextArea printerThree;
    private javax.swing.JTextArea printerTwo;
    private javax.swing.JTextField search;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JButton volver;
    private javax.swing.JButton volver1;
    private javax.swing.JButton volver2;
    private javax.swing.JButton volver3;
    // End of variables declaration//GEN-END:variables
}
